import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, readFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { generateWrapper, wrapperPath } from '../src/wrappers.ts';
import type { StdioServer } from '../src/schema.ts';

describe('generateWrapper', () => {
  it('generates a wrapper script with keychain resolution', () => {
    const server: StdioServer = {
      command: 'npx',
      args: ['@modelcontextprotocol/server-github'],
      env: {
        GITHUB_TOKEN: '${keychain:github-mcp-token}',
        PLAIN_VAR: 'hello',
      },
    };

    const result = generateWrapper('github', server, './mcp.json');

    expect(result.path).toContain('github.sh');
    expect(result.refs).toHaveLength(1);
    expect(result.refs[0]!.service).toBe('github-mcp-token');

    const content = readFileSync(result.path, 'utf8');
    expect(content).toContain('#!/bin/bash');
    expect(content).toContain('Auto-generated by mcp-sync');
    expect(content).toContain('security find-generic-password -s "github-mcp-token" -a "$USER" -w');
    expect(content).toContain('export PLAIN_VAR="hello"');
    expect(content).toContain('exec "npx" "@modelcontextprotocol/server-github"');
    expect(content).toContain('set -euo pipefail');
  });

  it('handles keychain ref with account override', () => {
    const server: StdioServer = {
      command: 'my-server',
      env: {
        API_KEY: '${keychain:api-key/myaccount}',
      },
    };

    const result = generateWrapper('myserver', server);
    const content = readFileSync(result.path, 'utf8');
    expect(content).toContain('security find-generic-password -s "api-key" -a "myaccount" -w');
  });

  it('handles multiple keychain refs in one env value', () => {
    const server: StdioServer = {
      command: 'my-server',
      env: {
        COMBINED: '${keychain:user}:${keychain:pass}',
      },
    };

    const result = generateWrapper('multi', server);
    expect(result.refs).toHaveLength(2);
    const content = readFileSync(result.path, 'utf8');
    expect(content).toContain('security find-generic-password -s "user"');
    expect(content).toContain('security find-generic-password -s "pass"');
  });

  it('generates executable wrapper', () => {
    const server: StdioServer = {
      command: 'test-cmd',
      env: { TOKEN: '${keychain:tok}' },
    };

    const result = generateWrapper('exectest', server);
    const { statSync } = require('fs');
    const stat = statSync(result.path);
    // Check owner execute permission
    expect(stat.mode & 0o100).toBe(0o100);
  });
});

describe('wrapperPath', () => {
  it('returns path in ~/.mcp-sync/wrappers/', () => {
    const p = wrapperPath('my-server');
    expect(p).toContain('.mcp-sync/wrappers/my-server.sh');
  });

  it('sanitizes server names', () => {
    const p = wrapperPath('my server/with$chars');
    expect(p).toContain('my_server_with_chars.sh');
  });
});
