import { mkdirSync, writeFileSync, chmodSync, unlinkSync, existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import type { StdioServer } from './schema.ts';
import {
  collectKeychainRefs,
  keychainResolveCommand,
  parseKeychainRefs,
  type KeychainRef,
} from './keychain.ts';

/** Directory where generated wrappers are stored */
export const WRAPPERS_DIR = join(homedir(), '.mcp-sync', 'wrappers');

/**
 * Ensure the wrappers directory exists with restrictive permissions.
 */
function ensureWrappersDir(): void {
  mkdirSync(WRAPPERS_DIR, { recursive: true, mode: 0o700 });
}

/**
 * Get the wrapper script path for a given server name.
 */
export function wrapperPath(serverName: string): string {
  // Sanitize server name for use as filename
  const safe = serverName.replace(/[^a-zA-Z0-9_-]/g, '_');
  return join(WRAPPERS_DIR, `${safe}.sh`);
}

export interface WrapperResult {
  /** Path to the generated wrapper script */
  path: string;
  /** The keychain refs that were resolved in this wrapper */
  refs: KeychainRef[];
}

/**
 * Generate a wrapper script for a stdio server that has ${keychain:...} references.
 * The wrapper resolves credentials from the Keychain at runtime and exec's the real command.
 */
export function generateWrapper(
  serverName: string,
  server: StdioServer,
  sourcePath?: string,
): WrapperResult {
  ensureWrappersDir();

  const env = server.env ?? {};
  const keychainEnvRefs = collectKeychainRefs(env);
  const allRefs: KeychainRef[] = [];

  // Build export lines for env vars with keychain refs
  const exportLines: string[] = [];

  for (const [envKey, value] of Object.entries(env)) {
    const refs = keychainEnvRefs.get(envKey);
    if (refs && refs.length > 0) {
      allRefs.push(...refs);
      // Replace each ${keychain:...} with the security command
      let resolved = value;
      for (const ref of refs) {
        resolved = resolved.replace(ref.match, keychainResolveCommand(ref));
      }
      exportLines.push(`export ${envKey}="${resolved}"`);
    } else {
      // Pass through non-keychain env vars as-is
      exportLines.push(`export ${envKey}="${value}"`);
    }
  }

  // Build the exec command
  const args = server.args ?? [];
  const quotedArgs = args.map(a => `"${a}"`).join(' ');
  const execLine = quotedArgs
    ? `exec "${server.command}" ${quotedArgs}`
    : `exec "${server.command}"`;

  const timestamp = new Date().toISOString();
  const sourceComment = sourcePath ? `# Source: ${sourcePath}\n` : '';

  const script = `#!/bin/bash
# Auto-generated by mcp-sync — do not edit
# Server: ${serverName}
${sourceComment}# Generated: ${timestamp}

set -euo pipefail

${exportLines.join('\n')}

${execLine}
`;

  const path = wrapperPath(serverName);
  writeFileSync(path, script, { mode: 0o700 });

  return { path, refs: allRefs };
}

/**
 * Remove a wrapper script for a server.
 */
export function removeWrapper(serverName: string): boolean {
  const path = wrapperPath(serverName);
  if (existsSync(path)) {
    unlinkSync(path);
    return true;
  }
  return false;
}
